[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.76"
authors = [ "kc9vu" ]
licence = "MIT"
license-file = "LICENSE"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-crypto = "0.2"
base64 = "0.22"

[workspace.dependencies.reqwest]
version = "0.11"
default-features = true
features = ["blocking", "json"]

[workspace.lints.rust]
unreachable_pub = "warn"

[profile.profiling]
inherits = "release"
debug = true

[profile.dist]
inherits = "release"
lto = "thin"
