[package]
name = "barsk"
version = "0.4.1"
edition = "2021"
authors = ["kc9vu"]
publish = false
description = "A bark cli written by Rust"
repository = "https://github.com/kc9vu/barsk"
readme = "README.md"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
openssl = { version = "0.10" }
percent-encoding = "2.3"

[profile.release]
lto = true
debug = false
strip = true
panic = "abort"
